spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d6mmrgn5gffc73bikerg-a.oregon-postgres.render.com/tododb_3rb4}
spring.datasource.username=${DB_USERNAME:todouser}
spring.datasource.password=${DB_PASSWORD:kCGQxrgbYZ7BEhSxLV1EsHsOfx6XPB2u}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}